POST http://localhost:9244/member/login HTTP/1.1 
content-type: application/json

{
   "miId" : "user16",
   "miPwd" : "92449244"
}
#################################################
PUT http://localhost:9244/member/join HTTP/1.1
content-type: application/json

{
  "miId" : "user17", 
  "miPwd" : "92449244", 
  "miEmail" : "user017@naver.com", 
  "miPhone" : "010-2000-9244", 
  "miNickname" : "차대준", 
  "miAddress" : "대구시 중구 삼덕동1가 1-5", 
  "miStatus" : "0"
}
#################################################
POST http://localhost:9244/member/searchId HTTP/1.1
content-type: application/json

{
   "miPhone" : "010-5017-1234"
}
#################################################
POST http://localhost:9244/member/searchPwd HTTP/1.1
content-type: application/json

{
   "miId" : "user16",
   "miPhone" : "010-5017-5773"
}
#################################################
POST http://localhost:9244/member/deleteMember HTTP/1.1
content-type: application/json

{
  "miPwd" : "92449244"
}
#################################################
PUT http://localhost:9244/review/write HTTP/1.1
content-type: application/json

{
"reRegDt" : "2023-01-10", 
"reScore" : 5, 
"reContent" : "맛있어요", 
"reOiSeq" : 4, 
"reTasteScore" : 5, 
"reQuantityScore" : 5, 
"reDeliveryScore" : 5, 
"riReSeq" : 4,
"riName" : "image3.jpg",
"riOrder" : 1 
}

