POST http://localhost:9244/member/login HTTP/1.1 
content-type: application/json

{
   "miId" : "user14",
   "miPwd" : "92449244"
}
#################################################
PUT http://localhost:9244/member/join HTTP/1.1
content-type: application/json

{
  "miId" : "user17", 
  "miPwd" : "92449244", 
  "miEmail" : "user017@naver.com", 
  "miPhone" : "010-9000-9244", 
  "miNickname" : "차대희", 
  "miAddress" : "대구시 중구 삼덕동1가 1-2", 
  "miStatus" : "0"
}
#################################################
POST http://localhost:9244/member/searchId HTTP/1.1
content-type: application/json

{
   "miPhone" : "010-9000-9244"
}
#################################################
POST http://localhost:9244/member/searchPwd HTTP/1.1
content-type: application/json

{
   "miId" : "user14",
   "miPhone" : "010-5017-1234"
}
#################################################
POST http://localhost:9244/member/deleteMember HTTP/1.1
content-type: application/json

{
  "miPwd" : "92449244"
}
#################################################
PUT http://localhost:9244/review/write HTTP/1.1
content-type: application/json

{
"regDt" : "2023-01-11", 
"score" : 5, 
"content" : "배달이 조금 늦는데 맛있어요", 
"oiSeq" : 5, 
"tasteScore" : 4, 
"quantityScore" : 5, 
"deliveryScore" : 4, 
"reSeq" : 6,
"name" : "image1.jpg",
"order" : 1 
}

